SchoolWeb/urls.py
from django.urls import path
from .import views

app_name = 'school'
urlpatterns = [
    path('',views.login, name='login'),
    path('home/',views.home, name='home'), 
    path('courses/',views.courses, name='courses'), 
    path('feedback/',views.feedback, name='feedback'),  
    path('post/',views.post, name='post'),  
    path('data/',views.data, name='data'),  
    path('addpost/',views.addpost, name='addpost'),   
]

school_dev/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('SchoolWeb.urls')), 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SchoolWeb/models.py
from django.db import models

# Create your models here.

class Home(models.Model):
    Login_home = models.CharField(max_length = 50)
    Courses = models.CharField(max_length = 50)
    Feedback = models.TextField()
    Image = models.ImageField(upload_to='images/', default='image/IMG3.JPG')
    
    def __str__(self):
        return self.Login_home

SchoolWeb/forms.py
from django import forms

from .models import Home

class Post_Form(forms.ModelForm):

    class Meta:
        model = Home
        fields = ['Login_home', 'Courses', 'Feedback']

SchoolWeb/views.py
from django.shortcuts import render
from .models import Home
from .forms import Post_Form
# Create your views here.


def login(request):
    age = 20
    context ={
        'age' : age 
        }
    return render(request,('SchoolWeb/login.html',context))

def home(request):
    return render(request,('SchoolWeb/home.html')) 

def courses(request):
    return render(request,('SchoolWeb/courses.html')) 

def feedback(request):
    return render(request,('SchoolWeb/feedback.html')) 

def data(request):
    datas = Home.objects.all()
    return render(request,'SchoolWeb/data.html',{'datas':datas}) 

def post(request):
    datas = Home.objects.all()
    return render(request,'SchoolWeb/post.html',{'datas':datas}) 
def addpost(request):
    if request.method == 'POST':
        form = Post_Form(request.POST)
        if form.is_valid():
            new_author =form.cleaned_data['Login_home']
            new_courses =form.cleaned_data['Courses']
            new_feedback =form.cleaned_data['Feedback']
    
    
    
        cleaned_post= Home(
            Login_home=new_author,
            Courses=new_courses,
            Feedback=new_feedback,
        )
        cleaned_post.save()
        return render(request,'SchoolWeb/addpost.html',{'form':Post_Form()}) 
    else:
        form = Post_Form()
        return render(request,'SchoolWeb/addpost.html',{
        'form':Post_Form()
        })
        
    

SchoolWeb/templates/SchoolWeb/addpost.html
{% extends "SchoolWeb/base.html" %}
{% load static %}
{% block content %}
<style>
    *{
        padding: 0px;
        margin: 0px;
        border: 0px;
        box-sizing: border-box;
    }   
    ul{
        text-align: center;
        background-color: white;
        background-image: url(/static/Image/gsIMG.jpg);
        background-repeat: no-repeat;
        background-size: contain;
        }
    ul li{
        display: inline-block;
        padding-top: 90px;
       padding-bottom: 6%;
    }
    ul li a{
        color: white;
        background-color: rgb(5, 117, 58);
        padding: 20px;
        text-decoration: none;
        border-radius: 5px;
    }
    ul li a:hover{
        color: rgb(12, 12, 12);
        background-color: rgb(185, 201, 8); 
    }
    .header{
        color: brown;
        text-align: center;
    }
    body{
        background-image: url(/static/Image/IMG.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        opacity: 0.7;
    }
</style>

<div>   
    <ul>
        <li><a href="{% url 'school:home' %}">Home</a></li>
        <li><a href="{% url 'school:courses' %}">Courses</a></li>
        <li><a href="{% url 'school:feedback' %}">Feedback</a></li>
        <li><a href="{% url 'school:data' %}">Data</a></li> 
        <li><a href="{% url 'school:post' %}">post</a></li> 
        <li><a href="{% url 'school:addpost' %}">addpost</a></li> 
    </ul> <br>
    </div> 
<body>
<div class="container">
    <div class="header">
        <h1>INTRODUCTION</h1>
    </div>
    <div class="logininput"> 
        <center>
          
        <form action="{% url 'school:addpost' %}" method="POST">
           
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-danger">upload</button>
        </form>
         
    


</body>








{% endblock content %}

SchoolWeb/templates/SchoolWeb/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'CSS/main.css' %}">  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"> 

    <title>Document</title>
</head>

    {% block content %}{% endblock content %} 

<br><br><br><br><br><br><br><br><br><br>
<p>
&copy; right by charles
</p>
</html>

SchoolWeb/templates/SchoolWeb/courses.html
{% extends "SchoolWeb/base.html" %}
{% load static %}
{% block title %}COURSES{% endblock title %} 
{% block content %}
<style>
    *{
        padding: 0px;
        margin: 0px;
        border: 0px;
        box-sizing: border-box;
    }   
    ul{
        text-align: center;
        background-color: white;
        background-image: url(/static/Image/gsIMG.jpg);
        background-repeat: no-repeat;
        background-size: contain;
        }
    ul li{
        display: inline-block;
        padding-top: 90px;
       padding-bottom: 6%;
    }
    ul li a{
        color: white;
        background-color: rgb(5, 117, 58);
        padding: 20px;
        text-decoration: none;
        border-radius: 5px;
    }
    ul li a:hover{
        color: rgb(12, 12, 12);
        background-color: rgb(185, 201, 8); 
    }
    .header{
        color: blue; 
        text-align: center;
    }
</style>
<body style="background-color:rgb(250, 209, 159)">
<div>
    <ul>
        <li><a href="{% url 'school:home' %}">Home</a></li> 
        <li><a href="{% url 'school:courses' %}">Courses</a></li>
        <li><a href="{% url 'school:feedback' %}">Feedback</a></li> 
        <li><a href="{% url 'school:data' %}">data</a></li> 
        <li><a href="{% url 'school:post' %}">post</a></li>
        <li><a href="{% url 'school:addpost' %}">addpost</a></li> 
    </ul> <br><br><br> 
</div>  
<center>  
    <h1 class="header">WHAT WE OFFER!</h1><br><br>
    <h1 class="header">MEDICINE</h1>
    <img src="{% static 'Image/IMG3.jpg' %}" alt="picture of medicine materials" height="400" width="600"> 
        <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
             Facere, explicabo officiis quae necessitatibus aliquid officia, tempora qui ab eaque eveniet, 
            inventore earum expedita impedit cumque rerum dolore nulla omnis sit.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
             Facere, explicabo officiis quae necessitatibus aliquid officia, tempora qui ab eaque eveniet, 
            inventore earum expedita impedit cumque rerum dolore nulla omnis sit.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
             Facere, explicabo officiis quae necessitatibus aliquid officia, tempora qui ab eaque eveniet, 
            inventore earum expedita impedit cumque rerum dolore nulla omnis sit.
        </p>
        <h1 class="header">COMPUTER SCIENCE</h1>
        <img src="{% static 'Image/IMG4.jpg' %}" alt="picture of computer science" height="400" width="600"> 
        <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
             Facere, explicabo officiis quae necessitatibus aliquid officia, tempora qui ab eaque eveniet, 
            inventore earum expedita impedit cumque rerum dolore nulla omnis sit.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
             Facere, explicabo officiis quae necessitatibus aliquid officia, tempora qui ab eaque eveniet, 
            inventore earum expedita impedit cumque rerum dolore nulla omnis sit.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
             Facere, explicabo officiis quae necessitatibus aliquid officia, tempora qui ab eaque eveniet, 
            inventore earum expedita impedit cumque rerum dolore nulla omnis sit.
        </p>
        <h1 class="header">LAW</h1>
        <img src="{% static 'Image/IMG5.jpg' %}" alt="law materials" height="400" width="600"> 
        <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
             Facere, explicabo officiis quae necessitatibus aliquid officia, tempora qui ab eaque eveniet, 
            inventore earum expedita impedit cumque rerum dolore nulla omnis sit.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
             Facere, explicabo officiis quae necessitatibus aliquid officia, tempora qui ab eaque eveniet, 
            inventore earum expedita impedit cumque rerum dolore nulla omnis sit.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
             Facere, explicabo officiis quae necessitatibus aliquid officia, tempora qui ab eaque eveniet, 
            inventore earum expedita impedit cumque rerum dolore nulla omnis sit.
        </p>
</center>
</div>
</body>

{% endblock content %}

SchoolWeb/templates/SchoolWeb/data.html
{% extends "SchoolWeb/base.html" %}
{% load static %}
{% block content %}
<style>
    *{
        padding: 0px;
        margin: 0px;
        border: 0px;
        box-sizing: border-box;
    }   
    ul{
        text-align: center;
        background-color: white;
        background-image: url(/static/Image/gsIMG.jpg);
        background-repeat: no-repeat;
        background-size: contain;
        }
    ul li{
        display: inline-block;
        padding-top: 90px;
       padding-bottom: 6%;
    }
    ul li a{
        color: white;
        background-color: rgb(5, 117, 58);
        padding: 20px;
        text-decoration: none;
        border-radius: 5px;
    }
    ul li a:hover{
        color: rgb(12, 12, 12);
        background-color: rgb(185, 201, 8); 
    }
    .header{
        color: brown;
        text-align: center;
    }
    body{
        background-image: url(/static/Image/IMG.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        opacity: 0.7;
    }
</style>
<div>   
    <ul>
        <li><a href="{% url 'school:home' %}">Home</a></li> 
        <li><a href="{% url 'school:courses' %}">Courses</a></li>
        <li><a href="{% url 'school:feedback' %}">Feedback</a></li>
        <li><a href="{% url 'school:data' %}">Data</a></li> 
        <li><a href="{% url 'school:post' %}">post</a></li>
        <li><a href="{% url 'school:addpost' %}">addpost</a></li>  
    </ul> <br>
    </div> 
<body>
<div class="container">
    <div class="header">
        <h1>INTRODUCTION</h1>
    </div>
    <div class="row md-3">
        {% for data in datas %}  
        <div class="col-md-3 mt-3" style="margin-left: 10%;">
            <div class="card" style="width: 18rem;">
                <img src="{{data.Image.url}}" class="card-img-top" alt="" height="200">
                <div class="card-body">
                    <h1>{{data.Login}}</h1>
                    <h3>{{data.Courses}}</h3>
                    <p>{{data.Feedback|truncatechars:50}}</p>
                    <a href="" class="btn btn-info">Read more</a> 
                </div>
            </div>
        </div>
        {% endfor%}
     


</body>








{% endblock content %}

SchoolWeb/templates/SchoolWeb/feedback.html
{% extends "SchoolWeb/base.html" %}
{% load static %}
{% block title %}FEEDBACK{% endblock title %}
{% block content %}
<style>
    *{
        padding: 0px;
        margin: 0px;
        border: 0px;
        box-sizing: border-box;
    }   
    ul{
        text-align: center;
        background-color: white;
        background-image: url(/static/Image/gsIMG.jpg);
        background-repeat: no-repeat;
        background-size: contain;
        }
    ul li{
        display: inline-block;
        padding-top: 90px;
       padding-bottom: 6%;
    }
    ul li a{
        color: white;
        background-color: rgb(5, 117, 58);
        padding: 20px;
        text-decoration: none;
        border-radius: 5px;
    }
    ul li a:hover{
        color: rgb(12, 12, 12);
        background-color: rgb(185, 201, 8); 
    }
    .header{
        color: brown;
        text-align: center;
    }
</style>
<body style="background-color: orange;"></body>
<ul>
    <li><a href="{% url 'school:home' %}">Home</a></li> 
    <li><a href="{% url 'school:courses' %}">Courses</a></li>
    <li><a href="{% url 'school:feedback' %}">Feedback</a></li> 
    <li><a href="{% url 'school:data' %}">Data</a></li>  
    <li><a href="{% url 'school:post' %}">post</a></li>
    <li><a href="{% url 'school:addpost' %}">addpost</a></li> 
</ul> <br><br><br>
<h1 class="header">WE WOULD TO HEAR FROM YOU!</h1>

<center><textarea name="" id="" cols="50" rows="20"></textarea><br>   
          <input type="submit">
</center><br><br>
<h1 class="header">OUR LOCATION!</h1>
<center><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15759.870507128675!2d7.4631486!3d9.0667137!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x104e0b1e59185243%3A0x7bb527554471700c!2sWuse%20Shopping%20Plaza!5e0!3m2!1sen!2sng!4v1706507548810!5m2!1sen!2sng" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></center>
</body>
{% endblock content %}

SchoolWeb/templates/SchoolWeb/home.html
{% extends "SchoolWeb/base.html" %}
{% load static %}
{% block title %}HOME{% endblock title %}
{% block content %}
<style>
    *{
        padding: 0px;
        margin: 0px;
        border: 0px;
        box-sizing: border-box;
    }
    ul{
        text-align: center;
        background-image: url(/static/Image/gsIMG.jpg);
        background-repeat: no-repeat;
        background-size: contain;
        background-color: white;
        }
    ul li{
        display: inline-block;
        padding-top: 90px;
        padding-bottom: 6%;
    }
    ul li a{
        color: rgb(250, 249, 249); 
        background-color: rgb(5, 131, 26);
        padding: 20px;
        text-decoration: none;
        border-radius: 5px;
        
    }
    ul li a:hover{
        color: rgb(12, 12, 12);
        background-color: rgb(223, 240, 61); 
    }
    body{
        background-color: aquamarine; 
    } 

</style>
<body>
<div>   
<ul>
    <li><a href="{% url 'school:home' %}">Home</a></li> 
    <li><a href="{% url 'school:courses' %}">Courses</a></li>
    <li><a href="{% url 'school:feedback' %}">Feedback</a></li>
    <li><a href="{% url 'school:data' %}">Data</a></li> 
    <li><a href="{% url 'school:post' %}">post</a></li>
    <li><a href="{% url 'school:addpost' %}">addpost</a></li> 
</ul> <br>
</div> 
<center>   
<h1 style="color: brown;">WHY YOU SHOULD CHOOSE GSKILLS UNIVERSITY</h1> 
<p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
</p>

<p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Voluptas officia, soluta accusantium delectus odio reiciendis facilis, labore neque ipsa
     amet esse saepe possimus eveniet quia accusamus laborum est perferendis similique.
</p>

<p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim quibusdam similique,
     molestias earum ab asperiores
     natus nisi ad eum perferendis ex incidunt vero doloremque alias, porro iste voluptatibus? Nemo, necessitatibus?
     Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim quibusdam similique,
     molestias earum ab asperiores
     natus nisi ad eum perferendis ex incidunt vero doloremque alias, porro iste voluptatibus? Nemo, necessitatibus?
</p>
</center>

{% endblock content %}

SchoolWeb/templates/SchoolWeb/login.html
{% extends "SchoolWeb/base.html" %}
{% load static %}
{% block title %}LOGIN{% endblock title %}
{% block content %}
<style>
    body{
        background-image:url(/static/Image/loginIMG1.jpg);
        background-repeat: no-repeat;
        background-size: cover;
    } 
    .logininput{
        background-image: url(/static/Image/loginIMG2.jpg); 
        display: inline-block;
        border-radius: 10%;
        margin-top: 17%;
        margin-left: 35%;
    }
    input{
        border-radius: 15%;
    }
</style>
<body>

    <div class="logininput"> 
    <center><form> 
        <h1 style="color: rgb(182, 182, 237);">LOGIN PAGE</h1>
        <input   type="text" placeholder="Username" size="25" class="form-control mb 3"><br><br>
        <input  type="password" placeholder="Password" size="50" class="form-control mb 3"> <br>  
        <a href="#">forgot password?</a>
        <br><br><br>
        <button style="background-color: rgb(52, 2, 61)"><a href="home" style="text-decoration: none;">LOGIN</a></button>
            </form></center> 
    </div>
</body>

{% endblock content %} 

SchoolWeb/templates/SchoolWeb/post.html
{% extends "SchoolWeb/base.html" %}
{% load static %}
{% block content %}
<style>
    *{
        padding: 0px;
        margin: 0px;
        border: 0px;
        box-sizing: border-box;
    }   
    ul{
        text-align: center;
        background-color: white;
        background-image: url(/static/Image/gsIMG.jpg);
        background-repeat: no-repeat;
        background-size: contain;
        }
    ul li{
        display: inline-block;
        padding-top: 90px;
       padding-bottom: 6%;
    }
    ul li a{
        color: white;
        background-color: rgb(5, 117, 58);
        padding: 20px;
        text-decoration: none;
        border-radius: 5px;
    }
    ul li a:hover{
        color: rgb(12, 12, 12);
        background-color: rgb(185, 201, 8); 
    }
    .header{
        color: brown;
        text-align: center;
    }
    body{
        background-image: url(/static/Image/IMG.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        opacity: 0.7;
    }
</style>
<div>   
    <ul>
        <li><a href="{% url 'school:home' %}">Home</a></li>
        <li><a href="{% url 'school:courses' %}">Courses</a></li>
        <li><a href="{% url 'school:feedback' %}">Feedback</a></li>
        <li><a href="{% url 'school:data' %}">Data</a></li> 
        <li><a href="{% url 'school:post' %}">post</a></li> 
        <li><a href="{% url 'school:addpost' %}">addpost</a></li> 
    </ul> <br>
    </div> 
<body>
<div class="container">
    <div class="header">
        <h1>INTRODUCTION</h1>
    </div>
    <div class="row md-3">
        {% for data in datas %}  
        <div class="col-md-3 mt-3" style="margin-left: 4%;">
            <div class="card" style="width: 18rem;">
                <img src="{{data.Image.url}}" class="card-img-top" alt="" height="200">
                <div class="card-body">
                    <h1>{{data.Login}}</h1>
                    <h3>{{data.Courses}}</h3>
                    <p>{{data.Feedback|truncatechars:50}}</p>
                    <a href="" class="btn btn-info">Read more</a> 
                </div>
            </div>
        </div>
        {% endfor%}
         
    


</body>








{% endblock content %}